import type { 
  NetworkFlow, 
  QoSPolicy, 
  ConnectedDevice, 
  AlertEvent, 
  ModelMetrics, 
  HistoricalDataPoint 
} from '../types/network';

export const INITIAL_DEVICES: ConnectedDevice[] = [
  {
    id: 'dev-laptop-1',
    name: 'Laptop 1 (Gateway)',
    role: 'Soft-AP Router & Sniffer Gateway',
    type: 'Laptop',
    ip: '192.168.137.1',
    mac: '00:1A:2B:3C:4D:5E',
    signalStrength: -38,
    currentSpeed: '124.5 Mbps',
    trafficType: 'Web Browsing',
    latency: 2.1,
    qosPriority: 'Medium',
    status: 'Online',
  },
  {
    id: 'dev-laptop-2',
    name: 'Laptop 2 (ML Engine)',
    role: 'ML Feature Pipeline & Model Engine',
    type: 'Laptop',
    ip: '192.168.137.2',
    mac: '00:1A:2B:3C:4D:5F',
    signalStrength: -40,
    currentSpeed: '45.2 Mbps',
    trafficType: 'Web Browsing',
    latency: 1.8,
    qosPriority: 'Medium',
    status: 'Online',
  },
  {
    id: 'dev-laptop-3',
    name: 'Laptop 3 (Dashboard)',
    role: 'Command & Demo Dashboard',
    type: 'Laptop',
    ip: '192.168.137.3',
    mac: '00:1A:2B:3C:4D:60',
    signalStrength: -42,
    currentSpeed: '12.8 Mbps',
    trafficType: 'Web Browsing',
    latency: 2.4,
    qosPriority: 'Medium',
    status: 'Online',
  },
  {
    id: 'dev-laptop-4',
    name: 'Laptop 4 (QoS Stressor)',
    role: 'QoS Controller & Traffic Stressor',
    type: 'Laptop',
    ip: '192.168.137.4',
    mac: '00:1A:2B:3C:4D:61',
    signalStrength: -44,
    currentSpeed: '8.4 Mbps',
    trafficType: 'Web Browsing',
    latency: 3.1,
    qosPriority: 'Medium',
    status: 'Online',
  },
  {
    id: 'dev-laptop-5',
    name: 'Laptop 5 (Sync Node)',
    role: 'Pitch Lead & Sync Node',
    type: 'Laptop',
    ip: '192.168.137.5',
    mac: '00:1A:2B:3C:4D:62',
    signalStrength: -45,
    currentSpeed: '4.2 Mbps',
    trafficType: 'Web Browsing',
    latency: 2.9,
    qosPriority: 'Medium',
    status: 'Online',
  },
  {
    id: 'dev-phone-1',
    name: 'Phone 1 (VoIP)',
    role: 'Discord / WhatsApp Voice Session',
    type: 'Phone',
    ip: '192.168.137.10',
    mac: '70:85:C2:A1:90:11',
    signalStrength: -52,
    currentSpeed: '0.25 Mbps',
    trafficType: 'VoIP',
    latency: 11.4,
    qosPriority: 'Highest',
    status: 'High Load',
  },
  {
    id: 'dev-phone-2',
    name: 'Phone 2 (Gaming)',
    role: 'PUBG Mobile / COD Mobile',
    type: 'Phone',
    ip: '192.168.137.12',
    mac: '70:85:C2:A1:90:12',
    signalStrength: -48,
    currentSpeed: '0.70 Mbps',
    trafficType: 'Gaming',
    latency: 14.8,
    qosPriority: 'High',
    status: 'High Load',
  },
  {
    id: 'dev-phone-3',
    name: 'Phone 3 (Streaming)',
    role: '4K Streaming (Netflix/YouTube)',
    type: 'Phone',
    ip: '192.168.137.15',
    mac: '70:85:C2:A1:90:15',
    signalStrength: -55,
    currentSpeed: '18.40 Mbps',
    trafficType: 'Streaming',
    latency: 28.6,
    qosPriority: 'Medium',
    status: 'High Load',
  },
  {
    id: 'dev-phone-4',
    name: 'Phone 4 (Download)',
    role: 'Steam Update Generator',
    type: 'Phone',
    ip: '192.168.137.18',
    mac: '70:85:C2:A1:90:18',
    signalStrength: -60,
    currentSpeed: '5.00 Mbps',
    trafficType: 'Background Download',
    latency: 118.0,
    qosPriority: 'Low',
    status: 'High Load',
  },
  {
    id: 'dev-phone-5',
    name: 'Phone 5 (OS Patch)',
    role: 'System Software Update',
    type: 'Phone',
    ip: '192.168.137.19',
    mac: '70:85:C2:A1:90:19',
    signalStrength: -62,
    currentSpeed: '4.85 Mbps',
    trafficType: 'Background Download',
    latency: 122.5,
    qosPriority: 'Low',
    status: 'Idle',
  },
];

export const INITIAL_FLOWS: NetworkFlow[] = [
  {
    id: 'flow-101',
    device: 'Phone 1 (VoIP)',
    ip: '192.168.137.10',
    srcPort: 50061,
    dstPort: 3478,
    protocol: 'UDP',
    trafficType: 'VoIP',
    predictedClass: 'VoIP',
    confidence: 0.988,
    currentSpeed: '0.25 Mbps',
    speedMbps: 0.25,
    latency: 11.4,
    qosPriority: 'Highest',
    dscp: 'DSCP 46 (EF)',
    status: 'Active',
    packetCount: 1420,
    byteCount: 184200,
    pktSizeMean: 130.0,
    pktSizeStd: 12.5,
    iatMean: 20.0,
    iatStd: 2.1,
    burstCount: 42,
    dirRatio: 0.92,
  },
  {
    id: 'flow-102',
    device: 'Phone 2 (Gaming)',
    ip: '192.168.137.12',
    srcPort: 54112,
    dstPort: 17000,
    protocol: 'UDP',
    trafficType: 'Gaming',
    predictedClass: 'Gaming',
    confidence: 0.974,
    currentSpeed: '0.70 Mbps',
    speedMbps: 0.70,
    latency: 14.8,
    qosPriority: 'High',
    dscp: 'DSCP 46 (EF)',
    status: 'Active',
    packetCount: 3890,
    byteCount: 520100,
    pktSizeMean: 133.7,
    pktSizeStd: 45.2,
    iatMean: 12.5,
    iatStd: 5.2,
    burstCount: 88,
    dirRatio: 0.85,
  },
  {
    id: 'flow-103',
    device: 'Phone 3 (Streaming)',
    ip: '192.168.137.15',
    srcPort: 49200,
    dstPort: 443,
    protocol: 'TCP',
    trafficType: 'Streaming',
    predictedClass: 'Streaming',
    confidence: 0.962,
    currentSpeed: '18.40 Mbps',
    speedMbps: 18.40,
    latency: 28.6,
    qosPriority: 'Medium',
    dscp: 'DSCP 26 (AF)',
    status: 'Active',
    packetCount: 12400,
    byteCount: 15400000,
    pktSizeMean: 1241.9,
    pktSizeStd: 80.5,
    iatMean: 2.1,
    iatStd: 0.5,
    burstCount: 310,
    dirRatio: 0.08,
  },
  {
    id: 'flow-104',
    device: 'Phone 4 (Download)',
    ip: '192.168.137.18',
    srcPort: 51240,
    dstPort: 80,
    protocol: 'TCP',
    trafficType: 'Background Download',
    predictedClass: 'Background Download',
    confidence: 0.991,
    currentSpeed: '5.00 Mbps',
    speedMbps: 5.00,
    latency: 118.0,
    qosPriority: 'Low',
    dscp: 'DSCP 8 (CS1)',
    status: 'Throttled',
    packetCount: 45200,
    byteCount: 61000000,
    pktSizeMean: 1349.5,
    pktSizeStd: 75.0,
    iatMean: 1.8,
    iatStd: 0.4,
    burstCount: 540,
    dirRatio: 0.03,
  },
  {
    id: 'flow-105',
    device: 'Laptop 1 (Gateway)',
    ip: '192.168.137.1',
    srcPort: 60124,
    dstPort: 443,
    protocol: 'TCP',
    trafficType: 'Video Call',
    predictedClass: 'Video Call',
    confidence: 0.958,
    currentSpeed: '3.40 Mbps',
    speedMbps: 3.40,
    latency: 18.2,
    qosPriority: 'High',
    dscp: 'DSCP 46 (EF)',
    status: 'Active',
    packetCount: 5200,
    byteCount: 4120000,
    pktSizeMean: 792.3,
    pktSizeStd: 110.4,
    iatMean: 15.2,
    iatStd: 4.1,
    burstCount: 65,
    dirRatio: 0.45,
  },
  {
    id: 'flow-106',
    device: 'Laptop 3 (Dashboard)',
    ip: '192.168.137.3',
    srcPort: 58810,
    dstPort: 443,
    protocol: 'TCP',
    trafficType: 'Web Browsing',
    predictedClass: 'Web Browsing',
    confidence: 0.945,
    currentSpeed: '1.20 Mbps',
    speedMbps: 1.20,
    latency: 8.5,
    qosPriority: 'Medium',
    dscp: 'DSCP 0 (Standard)',
    status: 'Normal',
    packetCount: 890,
    byteCount: 780000,
    pktSizeMean: 876.4,
    pktSizeStd: 210.2,
    iatMean: 45.0,
    iatStd: 12.8,
    burstCount: 12,
    dirRatio: 0.15,
  },
  {
    id: 'flow-107',
    device: 'Phone 5 (OS Patch)',
    ip: '192.168.137.19',
    srcPort: 44912,
    dstPort: 80,
    protocol: 'TCP',
    trafficType: 'Background Download',
    predictedClass: 'Background Download',
    confidence: 0.982,
    currentSpeed: '4.85 Mbps',
    speedMbps: 4.85,
    latency: 122.5,
    qosPriority: 'Low',
    dscp: 'DSCP 8 (CS1)',
    status: 'Throttled',
    packetCount: 38100,
    byteCount: 51200000,
    pktSizeMean: 1343.8,
    pktSizeStd: 72.1,
    iatMean: 1.9,
    iatStd: 0.45,
    burstCount: 480,
    dirRatio: 0.04,
  },
];

export const INITIAL_POLICIES: QoSPolicy[] = [
  {
    id: 'qos-gaming',
    trafficType: 'Gaming',
    priority: 'High',
    bandwidthAllocation: '20 Mbps',
    queue: 'Queue 1',
    dscpValue: 'DSCP 46',
    status: 'Active',
    tcFilterRule: 'tc class add dev wlan0 parent 1:1 classid 1:10 htb rate 20mbit ceil 100mbit prio 1',
    psRule: 'New-NetQosPolicy -Name "Gaming-Priority" -IPDstAddr 192.168.137.12 -DSCPAction 46 -ThrottleRateActionBitsPerSecond 20MB',
  },
  {
    id: 'qos-voip',
    trafficType: 'VoIP',
    priority: 'Highest',
    bandwidthAllocation: '10 Mbps',
    queue: 'Queue 1',
    dscpValue: 'DSCP 46',
    status: 'Active',
    tcFilterRule: 'tc class add dev wlan0 parent 1:1 classid 1:10 htb rate 10mbit ceil 100mbit prio 1',
    psRule: 'New-NetQosPolicy -Name "VoIP-Priority" -IPDstAddr 192.168.137.10 -DSCPAction 46 -ThrottleRateActionBitsPerSecond 10MB',
  },
  {
    id: 'qos-streaming',
    trafficType: 'Streaming',
    priority: 'Medium',
    bandwidthAllocation: '50 Mbps',
    queue: 'Queue 2',
    dscpValue: 'DSCP 26',
    status: 'Active',
    tcFilterRule: 'tc class add dev wlan0 parent 1:1 classid 1:20 htb rate 50mbit ceil 100mbit prio 2',
    psRule: 'New-NetQosPolicy -Name "Streaming-Medium" -IPDstAddr 192.168.137.15 -DSCPAction 26 -ThrottleRateActionBitsPerSecond 50MB',
  },
  {
    id: 'qos-background',
    trafficType: 'Background Download',
    priority: 'Low',
    bandwidthAllocation: '5 Mbps',
    queue: 'Queue 3',
    dscpValue: 'DSCP 8',
    status: 'Active',
    tcFilterRule: 'tc class add dev wlan0 parent 1:1 classid 1:30 htb rate 5mbit ceil 30mbit prio 3',
    psRule: 'New-NetQosPolicy -Name "Background-Throttled" -IPDstAddr 192.168.137.18 -DSCPAction 8 -ThrottleRateActionBitsPerSecond 5MB',
  },
  {
    id: 'qos-video-call',
    trafficType: 'Video Call',
    priority: 'High',
    bandwidthAllocation: '15 Mbps',
    queue: 'Queue 1',
    dscpValue: 'DSCP 46',
    status: 'Active',
    tcFilterRule: 'tc class add dev wlan0 parent 1:1 classid 1:10 htb rate 15mbit ceil 100mbit prio 1',
    psRule: 'New-NetQosPolicy -Name "VideoCall-Priority" -IPDstAddr 192.168.137.1 -DSCPAction 46 -ThrottleRateActionBitsPerSecond 15MB',
  },
  {
    id: 'qos-browsing',
    trafficType: 'Web Browsing',
    priority: 'Medium',
    bandwidthAllocation: '25 Mbps',
    queue: 'Queue 2',
    dscpValue: 'DSCP 0',
    status: 'Active',
    tcFilterRule: 'tc class add dev wlan0 parent 1:1 classid 1:20 htb rate 25mbit ceil 100mbit prio 2',
    psRule: 'New-NetQosPolicy -Name "WebBrowsing-Default" -IPDstAddr 192.168.137.3 -DSCPAction 0 -ThrottleRateActionBitsPerSecond 25MB',
  },
];

export const INITIAL_ALERTS: AlertEvent[] = [
  {
    id: 'alert-1',
    timestamp: '19:51:42',
    title: 'High Latency Spike Mitigated',
    description: 'Phone 4 initiated heavy TCP burst (Steam Update). QoS Engine throttled queue 1:30 to 5 Mbps, reducing latency from 340ms to 14.8ms.',
    severity: 'warning',
    category: 'High Latency',
  },
  {
    id: 'alert-2',
    timestamp: '19:50:18',
    title: 'QoS Policy Applied (DSCP 46)',
    description: 'Assigned Expedited Forwarding (EF) queue to Phone 1 (VoIP) & Phone 2 (Gaming).',
    severity: 'success',
    category: 'QoS Policy Applied',
  },
  {
    id: 'alert-3',
    timestamp: '19:48:05',
    title: 'Random Forest Model Inference Active',
    description: 'Processed 100,000 flow vectors with 96.4% classification accuracy. Avg inference latency: 3.2 ms.',
    severity: 'info',
    category: 'RF Prediction',
  },
  {
    id: 'alert-4',
    timestamp: '19:45:30',
    title: 'TCP MSS Clamping Enforced',
    description: 'Clamped Maximum Segment Size (MSS) to 1300 bytes on wlan0 hotspot interface to prevent bufferbloat serialization lag.',
    severity: 'success',
    category: 'TCP MSS Clamped',
  },
  {
    id: 'alert-5',
    timestamp: '19:41:12',
    title: 'New Device Connected to Hotspot',
    description: 'Device Phone 5 (192.168.137.19) authenticated on Soft-AP router. Initial 5-tuple feature extraction started.',
    severity: 'info',
    category: 'New Device',
  },
  {
    id: 'alert-6',
    timestamp: '19:38:00',
    title: 'TLS 1.3 SNI Mining Active',
    description: 'Extracted plaintext Client Hello domain SNIs to validate ground truth labels for Random Forest training dataset.',
    severity: 'info',
    category: 'RF Prediction',
  },
];

export const MODEL_METRICS_DATA: ModelMetrics = {
  accuracy: 96.4,
  predictionTimeMs: 3.2,
  treesCount: 100,
  status: 'Healthy',
  trainingDatasetLoaded: true,
  inferenceRunning: true,
  errorsCount: 0,
  featureImportance: [
    { feature: 'pkt_count', importance: 24.5, label: 'Packet Count' },
    { feature: 'byte_count', importance: 21.2, label: 'Byte Count' },
    { feature: 'pkt_size_mean', importance: 18.8, label: 'Average Packet Size' },
    { feature: 'pkt_size_std', importance: 14.1, label: 'Packet Size Std' },
    { feature: 'iat_mean', importance: 11.4, label: 'Inter-arrival Time (IAT)' },
    { feature: 'burst_count', importance: 6.2, label: 'Burst Count (<5ms)' },
    { feature: 'dir_ratio', importance: 3.8, label: 'Direction Ratio (Uplink/Downlink)' },
  ],
  confusionMatrix: [
    { actual: 'Gaming', Gaming: 98, VoIP: 1, Streaming: 0, Background: 0, Browsing: 1 },
    { actual: 'VoIP', Gaming: 1, VoIP: 99, Streaming: 0, Background: 0, Browsing: 0 },
    { actual: 'Streaming', Gaming: 0, VoIP: 0, Streaming: 95, Background: 3, Browsing: 2 },
    { actual: 'Background', Gaming: 0, VoIP: 0, Streaming: 2, Background: 97, Browsing: 1 },
    { actual: 'Browsing', Gaming: 2, VoIP: 0, Streaming: 3, Background: 2, Browsing: 93 },
  ],
};

export const INITIAL_HISTORICAL_DATA: HistoricalDataPoint[] = [
  { time: '19:42:00', latencyRaw: 180, latencyOptimized: 14.2, bandwidthMbps: 42.1, packetCount: 8500, cpuUsage: 8.2, memoryUsage: 398, gamingMbps: 0.7, voipMbps: 0.25, streamingMbps: 12.4, downloadMbps: 25.0, browsingMbps: 3.75 },
  { time: '19:43:00', latencyRaw: 240, latencyOptimized: 15.0, bandwidthMbps: 58.4, packetCount: 11200, cpuUsage: 10.4, memoryUsage: 402, gamingMbps: 0.7, voipMbps: 0.25, streamingMbps: 15.2, downloadMbps: 38.0, browsingMbps: 4.25 },
  { time: '19:44:00', latencyRaw: 350, latencyOptimized: 14.5, bandwidthMbps: 84.5, packetCount: 14820, cpuUsage: 12.4, memoryUsage: 412, gamingMbps: 0.7, voipMbps: 0.25, streamingMbps: 18.4, downloadMbps: 60.0, browsingMbps: 5.15 },
  { time: '19:45:00', latencyRaw: 310, latencyOptimized: 13.8, bandwidthMbps: 78.2, packetCount: 13900, cpuUsage: 11.8, memoryUsage: 410, gamingMbps: 0.7, voipMbps: 0.25, streamingMbps: 18.0, downloadMbps: 54.0, browsingMbps: 5.25 },
  { time: '19:46:00', latencyRaw: 290, latencyOptimized: 14.1, bandwidthMbps: 72.0, packetCount: 12800, cpuUsage: 11.2, memoryUsage: 408, gamingMbps: 0.7, voipMbps: 0.25, streamingMbps: 16.5, downloadMbps: 50.0, browsingMbps: 4.55 },
  { time: '19:47:00', latencyRaw: 340, latencyOptimized: 14.8, bandwidthMbps: 82.0, packetCount: 14200, cpuUsage: 12.1, memoryUsage: 415, gamingMbps: 0.7, voipMbps: 0.25, streamingMbps: 18.1, downloadMbps: 58.0, browsingMbps: 4.95 },
  { time: '19:48:00', latencyRaw: 320, latencyOptimized: 14.2, bandwidthMbps: 80.5, packetCount: 14100, cpuUsage: 12.0, memoryUsage: 414, gamingMbps: 0.7, voipMbps: 0.25, streamingMbps: 18.0, downloadMbps: 56.5, browsingMbps: 5.05 },
  { time: '19:49:00', latencyRaw: 360, latencyOptimized: 14.0, bandwidthMbps: 86.2, packetCount: 15100, cpuUsage: 12.8, memoryUsage: 418, gamingMbps: 0.7, voipMbps: 0.25, streamingMbps: 18.8, downloadMbps: 61.2, browsingMbps: 5.25 },
  { time: '19:50:00', latencyRaw: 330, latencyOptimized: 13.9, bandwidthMbps: 83.1, packetCount: 14500, cpuUsage: 12.3, memoryUsage: 416, gamingMbps: 0.7, voipMbps: 0.25, streamingMbps: 18.2, downloadMbps: 58.9, browsingMbps: 5.05 },
  { time: '19:51:00', latencyRaw: 355, latencyOptimized: 14.2, bandwidthMbps: 84.5, packetCount: 14820, cpuUsage: 12.4, memoryUsage: 412, gamingMbps: 0.7, voipMbps: 0.25, streamingMbps: 18.4, downloadMbps: 60.1, browsingMbps: 5.05 },
];

export const TRAFFIC_DISTRIBUTION = [
  { name: 'Streaming', value: 45, color: '#2563EB', speed: '18.4 Mbps' },
  { name: 'Background Download', value: 30, color: '#64748B', speed: '10.0 Mbps (Capped)' },
  { name: 'Gaming', value: 10, color: '#22C55E', speed: '0.70 Mbps' },
  { name: 'VoIP', value: 8, color: '#06B6D4', speed: '0.25 Mbps' },
  { name: 'Web Browsing', value: 7, color: '#F59E0B', speed: '4.60 Mbps' },
];
